"""Init

Revision ID: 289d2b8bf889
Revises: 
Create Date: 2025-02-17 11:41:38.395637

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '289d2b8bf889'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('esta_empregado', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Cargos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=False),
    sa.Column('pessoa_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['pessoa_id'], ['Pessoa.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Cargos')
    op.drop_table('Pessoa')
    # ### end Alembic commands ###
