"""empty message

Revision ID: 39c8302873a1
Revises: 
Create Date: 2025-02-19 05:59:01.831468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39c8302873a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Trabalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Pessoa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('trabalho_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['trabalho_id'], ['Trabalho.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Pessoa')
    op.drop_table('Trabalho')
    # ### end Alembic commands ###
